using System;
using System.Collections.Generic;

namespace GoldMeridian.PaintLabel;

public static class OpcodeTypeInfo
{
    public static Dictionary<ShaderOpcode, OpcodeTypeInfo<ShaderOpcode>> Opcodes { get; } = new()
    {
        [ShaderOpcode.Nop] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Nop),
        [ShaderOpcode.Mov] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Mov),
        [ShaderOpcode.Add] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Add),
        [ShaderOpcode.Sub] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Sub),
        [ShaderOpcode.Mad] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Mad),
        [ShaderOpcode.Mul] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Mul),
        [ShaderOpcode.Rcp] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Rcp),
        [ShaderOpcode.Rsq] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Rsq),
        [ShaderOpcode.Dp3] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Dp3),
        [ShaderOpcode.Dp4] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Dp4),
        [ShaderOpcode.Min] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Min),
        [ShaderOpcode.Max] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Max),
        [ShaderOpcode.Slt] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Slt),
        [ShaderOpcode.Sge] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Sge),
        [ShaderOpcode.Exp] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Exp),
        [ShaderOpcode.Log] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Log),
        [ShaderOpcode.Lit] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Lit),
        [ShaderOpcode.Dst] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Dst),
        [ShaderOpcode.Lrp] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Lrp),
        [ShaderOpcode.Frc] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Frc),
        [ShaderOpcode.M4X4] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.M4X4),
        [ShaderOpcode.M4X3] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.M4X3),
        [ShaderOpcode.M3X4] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.M3X4),
        [ShaderOpcode.M3X3] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.M3X3),
        [ShaderOpcode.M3X2] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.M3X2),
        [ShaderOpcode.Call] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Call),
        [ShaderOpcode.CallNz] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.CallNz),
        [ShaderOpcode.Loop] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Loop),
        [ShaderOpcode.Ret] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Ret),
        [ShaderOpcode.Endloop] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Endloop),
        [ShaderOpcode.Label] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Label),
        [ShaderOpcode.Dcl] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Dcl),
        [ShaderOpcode.Pow] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Pow),
        [ShaderOpcode.Crs] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Crs),
        [ShaderOpcode.Sgn] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Sgn),
        [ShaderOpcode.Abs] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Abs),
        [ShaderOpcode.Nrm] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Nrm),
        [ShaderOpcode.Sincos] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Sincos),
        [ShaderOpcode.Rep] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Rep),
        [ShaderOpcode.EndRep] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.EndRep),
        [ShaderOpcode.If] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.If, NoDest: true),
        [ShaderOpcode.IfC] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.IfC, NoDest: true),
        [ShaderOpcode.Else] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Else, NoDest: true),
        [ShaderOpcode.Endif] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Endif, NoDest: true),
        [ShaderOpcode.Break] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Break, NoDest: true),
        [ShaderOpcode.BreakC] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.BreakC, NoDest: true),
        [ShaderOpcode.MovA] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.MovA),
        [ShaderOpcode.DefB] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.DefB),
        [ShaderOpcode.DefI] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.DefI),
        [ShaderOpcode.TexCrd] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexCrd),
        [ShaderOpcode.TexKill] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexKill),
        [ShaderOpcode.TexLd] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexLd),
        [ShaderOpcode.TexBem] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexBem),
        [ShaderOpcode.TexBemL] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexBemL),
        [ShaderOpcode.TexReg2Ar] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexReg2Ar),
        [ShaderOpcode.TexReg2Gb] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexReg2Gb),
        [ShaderOpcode.TexM3X2Pad] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexM3X2Pad),
        [ShaderOpcode.TexM3X2Tex] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexM3X2Tex),
        [ShaderOpcode.TexM3X3Pad] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexM3X3Pad),
        [ShaderOpcode.TexM3X3Tex] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexM3X3Tex),
        [ShaderOpcode.TexM3X3Spec] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexM3X3Spec),
        [ShaderOpcode.TexM3X3VSpec] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexM3X3VSpec),
        [ShaderOpcode.ExpP] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.ExpP),
        [ShaderOpcode.LogP] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.LogP),
        [ShaderOpcode.Cnd] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Cnd),
        [ShaderOpcode.Def] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Def),
        [ShaderOpcode.TexReg2Rgb] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexReg2Rgb),
        [ShaderOpcode.TexDp3Tex] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexDp3Tex),
        [ShaderOpcode.TexM3X2Depth] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexM3X2Depth),
        [ShaderOpcode.TexDp3] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexDp3),
        [ShaderOpcode.TexM3X3] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexM3X3),
        [ShaderOpcode.TexDepth] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexDepth),
        [ShaderOpcode.Cmp] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Cmp),
        [ShaderOpcode.Bem] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Bem),
        [ShaderOpcode.Dp2Add] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Dp2Add),
        [ShaderOpcode.Dsx] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Dsx),
        [ShaderOpcode.Dsy] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.Dsy),
        [ShaderOpcode.TexLdd] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexLdd),
        [ShaderOpcode.SetP] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.SetP),
        [ShaderOpcode.TexLdl] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.TexLdl),
        [ShaderOpcode.BreakP] = new OpcodeTypeInfo<ShaderOpcode>(ShaderOpcode.BreakP),
    };

    public static Dictionary<PreshaderOpcode, OpcodeTypeInfo<PreshaderOpcode>> PreshaderOpcodes { get; } = new()
    {
        [PreshaderOpcode.Nop] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Nop),
        [PreshaderOpcode.Mov] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Mov),
        [PreshaderOpcode.Neg] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Neg),
        [PreshaderOpcode.Rcp] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Rcp),
        [PreshaderOpcode.Frc] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Frc),
        [PreshaderOpcode.Exp] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Exp),
        [PreshaderOpcode.Log] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Log),
        [PreshaderOpcode.Rsq] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Rsq),
        [PreshaderOpcode.Sin] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Sin),
        [PreshaderOpcode.Cos] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Cos),
        [PreshaderOpcode.Asin] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Asin),
        [PreshaderOpcode.Acos] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Acos),
        [PreshaderOpcode.Atan] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Atan),
        [PreshaderOpcode.Min] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Min),
        [PreshaderOpcode.Max] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Max),
        [PreshaderOpcode.Lt] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Lt),
        [PreshaderOpcode.Ge] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Ge),
        [PreshaderOpcode.Add] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Add),
        [PreshaderOpcode.Mul] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Mul),
        [PreshaderOpcode.Atan2] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Atan2),
        [PreshaderOpcode.Div] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Div),
        [PreshaderOpcode.Cmp] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Cmp),
        [PreshaderOpcode.MovC] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.MovC),
        [PreshaderOpcode.Dot] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Dot),
        [PreshaderOpcode.Noise] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Noise),
        [PreshaderOpcode.MinScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.MinScalar),
        [PreshaderOpcode.MaxScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.MaxScalar),
        [PreshaderOpcode.LtScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.LtScalar),
        [PreshaderOpcode.GeScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.GeScalar),
        [PreshaderOpcode.AddScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.AddScalar),
        [PreshaderOpcode.MulScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.MulScalar),
        [PreshaderOpcode.Atan2Scalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.Atan2Scalar),
        [PreshaderOpcode.DivScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.DivScalar),
        [PreshaderOpcode.DotScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.DotScalar),
        [PreshaderOpcode.NoiseScalar] = new OpcodeTypeInfo<PreshaderOpcode>(PreshaderOpcode.NoiseScalar),
    };
}

public readonly record struct OpcodeTypeInfo<TKind>(TKind Type, bool NoDest = false)
    where TKind : struct, Enum;
