namespace GoldMeridian.PaintLabel;

// Not in order according to D3D.  Uses mojoshader's reordered data:
// - all the Wrap values are in a row, not separate.
public enum HlslRenderStateType
{
    ZEnable,
    FillMode,
    ShadeMode,
    ZWriteEnable,
    AlphaTestEnable,
    LastPixel,
    SrcBlend,
    DestBlend,
    CullMode,
    ZFunc,
    AlphaRef,
    AlphaFunc,
    DitherEnable,
    AlphaBlendEnable,
    FogEnable,
    SpecularEnable,
    FogColor,
    FogTableMode,
    FogStart,
    FogEnd,
    FogDensity,
    RangeFogEnable,
    StencilEnable,
    StencilFail,
    StencilZFail,
    StencilPass,
    StencilFunc,
    StencilRef,
    StencilMask,
    StencilWriteMask,
    TextureFactor,
    Wrap0,
    Wrap1,
    Wrap2,
    Wrap3,
    Wrap4,
    Wrap5,
    Wrap6,
    Wrap7,
    Wrap8,
    Wrap9,
    Wrap10,
    Wrap11,
    Wrap12,
    Wrap13,
    Wrap14,
    Wrap15,
    Clipping,
    Lighting,
    Ambient,
    FogVertexMode,
    ColorVertex,
    LocalViewer,
    NormalizeNormals,
    DiffuseMaterialSource,
    SpecularMaterialSource,
    AmbientMaterialSource,
    EmissiveMaterialSource,
    VertexBlend,
    ClipPlaneEnable,
    PointSize,
    PointSizeMin,
    PointSpriteEnable,
    PointScaleEnable,
    PointScaleA,
    PointScaleB,
    PointScaleC,
    MultiSampleAntiAlias,
    MultiSampleMask,
    PatchEdgeStyle,
    DebugMonitorToken,
    PointSizeMax,
    IndexedVertexBlendEnable,
    ColorWriteEnable,
    TweenFactor,
    BlendOp,
    PositionDegree,
    NormalDegree,
    ScissorTestEnable,
    SlopeScaleDepthBias,
    AntiAliasedLineEnable,
    MinTessellationLevel,
    MaxTessellationLevel,
    AdaptiveTessX,
    AdaptiveTessY,
    AdaptiveTessZ,
    AdaptiveTessW,
    EnableAdaptiveTessellation,
    TwoSidedStencilMode,
    CcwStencilFail,
    CcwStencilZFail,
    CcwStencilPass,
    CcwStencilFunc,
    ColorWriteEnable1,
    ColorWriteEnable2,
    ColorWriteEnable3,
    BlendFactor,
    SrgbWriteEnable,
    DepthBias,
    SeparateAlphaBlendEnable,
    SrcBlendAlpha,
    DestBlendAlpha,
    BlendOpAlpha,

    // mojoshader says these aren't "states", but are numbers that get used by
    // HlslEffectStateType.
    VertexShader = 146,
    PixelShader = 147,
}

public readonly record struct HlslEffectState(
    HlslRenderStateType Type,
    HlslEffectValue Value
);

public readonly record struct HlslEffectPass(
    string Name,
    HlslEffectState[] States,
    HlslEffectAnnotation[] Annotations
);

public readonly record struct HlslEffectTechnique(
    string Name,
    HlslEffectPass Passes,
    HlslEffectAnnotation[] Annotations
);
